# Basic
title: Rdd7
subtitle: iOS Dev Blog
description: iOS开发者，就职于网易，正在努力丰富iOS技能与经验.
creator: <a href="http://rdd7.com">@rdd7</a>

url: "https://rdd7.github.io"

permalink: /:year/:month/:title/

# Format
highlighter: plain

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: slate

# The blog button should not be removed.
blog_button:
    title: Blog
    description: Visit blog

# Navigation buttons in the front page.
nav:
    - {title: Github, description: Github, url: 'http://rdd7.github.com'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
#comment:
#    disqus: vno-jekyll
    # duoshuo: 
    
# Social
social:
#    weibo: rdd7
    github: rdd7
#    twitter: rdd7
#    gplus: 
    mail: rdd7@rdd7.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
